theme: jekyll-theme-dinky
markdown: kramdown
mathjax_autoNumber: true
mermaid: true
chart: true
highlighter: rouge
plugins:
  - jekyll-toc
kramdown:
  input:  GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


algolia:
  application_id: 'YL1VF8ZXL2' 
  index_name: jekyll # You can replace that with whatever name you want  
  search_only_api_key: 883eb7b32d107ab889ebdbd54a45d347  